### PR TITLE
Fixes a bug on `allButterContent `

### LINKED ISSUE #9: issue with inconsistent values on type `allButterContent`
`allButterContent` isn't working correctly.

Basically, there are conflicting field types that is causing the fields to be omitted by Graphql.  This is as a result of the inconsistent values that was used in creating nodes.

errgql

graphql requires that nodes of same type should have values of same type else it drops the fields affected.

E.g 

Content Field 

```
{
  key: "faq_headline",
  value: "Frequently Asked Question"
}
```

Collection

```
{
  key: "faq_items"
  value: [
    {question: "", answer: ""},
    ......
  ]
}
```

Graphql won't accept those inconsistencies. value should be of same type.

**Recommended Fix**
Separating `Collection` type from `ContentField` 

i.e
allButterCollection
allButterContentField

So on the backend those types remain the same only that the plugin trys to sepate them

### PR DESCRIPTION
**Pull request by marvinjude**
Fixes #9 

removes type `allButterContent`

adds type `allButterContentField` and `allButterCollection `  to fix bug #9

### CODE REVIEW

File: src/gatsby-node.js [hunk 1]
```diff
@@ -76,23 +90,75 @@ exports.sourceNodes = async (
...
-        const gatsbyContentField = Object.assign({}, key, value, {
+
+      const entries = Object.entries(contentFieldsResult.data.data)
+
+      let allCollection = [],
+        allfields = [];
+
+      //Extract Collections and Content Fields into separate variables
+      entries.forEach(([key, value]) => {
+        if (typeof (value) == "object") {
```
Comment (jakelumetta) [inline src/gatsby-node.js]: For a collection, `value` will be an array so this comparison doesn't seem correct.

**Comment by jakelumetta** [comment]
Looks good, thanks!
